
package Vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import pokemon.conectar;

public class tablaEntrenador extends javax.swing.JFrame {
conectar cc=new conectar();
Connection con=cc.con;

    
    public tablaEntrenador() {
             
        initComponents();
        
           setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Pokemon");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
       ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/donfo.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        mostrarDatos();
        
         noVisibles();
         
        
        
    }
    
    public void noVisibles(){
        this.txt_nom.setVisible(false);
        this.txt_apell.setVisible(false);
        this.txt_fech.setVisible(false);
        this.txt_med.setVisible(false);
        this.rd_V.setVisible(false);
        this.rd_F.setVisible(false);
        this.bt_guardar.setVisible(false);
        this.icon.setVisible(true);
        
        this.lb1.setVisible(false);
        this.lb2.setVisible(false);
        this.lb3.setVisible(false);
        this.lb4.setVisible(false);
        this.lb5.setVisible(false);
     
    }
    public void visibles(){
        this.txt_nom.setVisible(true);
        this.txt_apell.setVisible(true);
        this.txt_fech.setVisible(true);
        this.txt_med.setVisible(true);
        this.rd_V.setVisible(true);
        this.rd_F.setVisible(true);
        this.bt_guardar.setVisible(true);
        this.icon.setVisible(false);
        
        this.lb1.setVisible(true);
        this.lb2.setVisible(true);
        this.lb3.setVisible(true);
        this.lb4.setVisible(true);
        this.lb5.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        bt_eliminar = new javax.swing.JButton();
        bt_actualizar = new javax.swing.JButton();
        bt_nuevo = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        txt_apell = new javax.swing.JTextField();
        lb3 = new javax.swing.JLabel();
        txt_fech = new javax.swing.JTextField();
        lb4 = new javax.swing.JLabel();
        txt_med = new javax.swing.JTextField();
        lb5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_busquar = new javax.swing.JTextField();
        bt_guardar = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rd_V = new javax.swing.JRadioButton();
        rd_F = new javax.swing.JRadioButton();
        lb_v = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        tabla.setBackground(new java.awt.Color(153, 204, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_actualizar.setText("Actualizar");
        bt_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizarActionPerformed(evt);
            }
        });

        bt_nuevo.setText("Nuevo");
        bt_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevoActionPerformed(evt);
            }
        });

        lb1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("Nombre:");

        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });

        lb2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setText("Apellido:");

        lb3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 255));
        lb3.setText("Fecha de Nacimiento:");

        lb4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 255, 255));
        lb4.setText("Numero de medallas:");

        lb5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 255, 255));
        lb5.setText("Campeon actual:");

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel2.setText("Entrenadores Pokemon");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUSQUEDA:");

        txt_busquar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_busquarActionPerformed(evt);
            }
        });
        txt_busquar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busquarKeyReleased(evt);
            }
        });

        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\ashf.gif")); // NOI18N

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rd_V.setForeground(new java.awt.Color(255, 255, 255));

        lb_v.setForeground(new java.awt.Color(255, 255, 255));
        lb_v.setText("Verdadero");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Falso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addComponent(txt_busquar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb1)
                                    .addComponent(lb3)
                                    .addComponent(lb4)
                                    .addComponent(lb5))
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(lb_v))
                                            .addComponent(rd_V))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rd_F)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_fech, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_med, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_apell, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(bt_guardar)
                                .addGap(27, 27, 27)))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(bt_eliminar)
                .addGap(68, 68, 68)
                .addComponent(bt_actualizar)
                .addGap(75, 75, 75)
                .addComponent(bt_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(icon)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_busquar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_nuevo)
                    .addComponent(bt_eliminar)
                    .addComponent(jButton1)
                    .addComponent(bt_actualizar))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb1)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_apell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb3)
                            .addComponent(txt_fech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(bt_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb4)
                    .addComponent(txt_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_v)
                        .addComponent(rd_V)
                        .addComponent(lb5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(rd_F))
                        .addGap(7, 7, 7)))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    public void limpiar(){
        txt_nom.setText("");
        txt_apell.setText("");
        txt_fech.setText("");
        txt_med.setText("");
        rd_V.setText("");
        rd_F.setText("");
        
       
        
    }
     public void actualizarDatos(){
         conectar cc = new conectar();
        Connection cn = cc.con;
        String id, nom, apell, fech, med, camp;
        String sql ="";
   
        nom = txt_nom.getText();
        apell = txt_apell.getText();
        fech = txt_fech.getText();
        med = txt_med.getText();
        
        sql ="update entrenador set nombre=?, apellido=?, fecha_nacimiento=?, numero_medallas=?, campeon_actual=? where id=?";
      
        int filaSelec=tabla.getSelectedRow();       
        String dao=(String)tabla.getValueAt(filaSelec, 0);
        
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
          
            pst.setString(1, nom);
            pst.setString(2, apell);
            pst.setString(3, fech);
            pst.setString(4, med);
            pst.setString(5, campeon);
            pst.setString(6, dao);
            
            int n=pst.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(null, "Resgistro editado con exito");
                noVisibles();
            }
        } catch (SQLException ex) {
            Logger.getLogger(entrenador.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }
  
    public void agregarDatos(){
         conectar cc = new conectar();
        Connection cn = cc.con;
        String id, nom, apell, fech, med, camp;
        String sql ="";
   
        nom = txt_nom.getText();
        apell = txt_apell.getText();
        fech = txt_fech.getText();
        med = txt_med.getText();
       
        sql ="INSERT INTO entrenador (nombre, apellido, fecha_nacimiento, numero_medallas, campeon_actual) VALUES (?, ?, ?, ?, ?)";
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
          
            pst.setString(1, nom);
            pst.setString(2, apell);
            pst.setString(3, fech);
            pst.setString(4, med);
            pst.setString(5, campeon);
            int n=pst.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(null, "Resgistro guardado con exito");
                noVisibles();
            }
        } catch (SQLException ex) {
            Logger.getLogger(entrenador.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }
  
    
    
    public void mostrarDatos(){
               

        String[] titulos={"ID", "Nombre", "Apellido", "Fecha Nacimiento", "Numero medallas", "Campeon Actual"};
        String[] registros=new String[7];
        
        DefaultTableModel modelo=new DefaultTableModel(null,titulos);
        
        String sql="select * from entrenador";
        
        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            
          while(rs.next()){
              
              registros[0]=rs.getString("id");
              registros[1]=rs.getString("nombre");
              registros[2]=rs.getString("apellido");
              registros[3]=rs.getString("fecha_nacimiento");
              registros[4]=rs.getString("numero_medallas");
              registros[5]=rs.getString("campeon_actual");
              
              modelo.addRow(registros);
              
          }
          tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror al mostrar datos" +e.getMessage());
        }
    }
     public void filtrarDatos(String valor){
               

        String[] titulos={"ID", "Nombre", "Apellido", "Fecha Nacimiento", "Numero medallas", "Campeon Actual"};
        String[] registros=new String[7];
        
        DefaultTableModel modelo=new DefaultTableModel(null,titulos);
        
        String sql="select * from entrenador where nombre like '%"+valor+"%'";
        
        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            
          while(rs.next()){
              
              registros[0]=rs.getString("id");
              registros[1]=rs.getString("nombre");
              registros[2]=rs.getString("apellido");
              registros[3]=rs.getString("fecha_nacimiento");
              registros[4]=rs.getString("numero_medallas");
              registros[5]=rs.getString("campeon_actual");
              
              modelo.addRow(registros);
              
          }
          tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror al mostrar datos" +e.getMessage());
        }
    }
    private void bt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevoActionPerformed

     visibles();
     limpiar();
     mostrarDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_nuevoActionPerformed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        limpiar();
        agregarDatos();
        mostrarDatos();// TODO add your handling code here:
    }//GEN-LAST:event_bt_guardarActionPerformed
public void eliminar(){
     int filaSelec=tabla.getSelectedRow();  
     try {
        String sql="delete from entrenador where id="+tabla.getValueAt(filaSelec,0);
        
        Statement st=con.createStatement();
        
        int n=st.executeUpdate(sql);
        
        if(n>=0){
            JOptionPane.showMessageDialog(null, "Registro eliminado");
            
        }
        
    } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Error al eliminadar registro"+e.getMessage());
            
    }
}
    private void bt_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizarActionPerformed

actualizarDatos();
limpiar();
mostrarDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_actualizarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int filaSelec=tabla.rowAtPoint(evt.getPoint());
        
        txt_nom.setText(tabla.getValueAt(filaSelec,1).toString());
        txt_apell.setText(tabla.getValueAt(filaSelec,2).toString());
        txt_fech.setText(tabla.getValueAt(filaSelec,3).toString());
        txt_med.setText(tabla.getValueAt(filaSelec,4).toString());
       
        
        
        
        
    }//GEN-LAST:event_tablaMouseClicked

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed

eliminar();
mostrarDatos();
limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void txt_busquarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_busquarActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busquarActionPerformed

    private void txt_busquarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquarKeyReleased

        filtrarDatos(txt_busquar.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busquarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed



                    Sistema op=new Sistema();
                    op.setVisible(true);
                    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablaEntrenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_nuevo;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb_v;
    private javax.swing.JRadioButton rd_F;
    private javax.swing.JRadioButton rd_V;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txt_apell;
    private javax.swing.JTextField txt_busquar;
    private javax.swing.JTextField txt_fech;
    private javax.swing.JTextField txt_med;
    private javax.swing.JTextField txt_nom;
    // End of variables declaration//GEN-END:variables
private String campeon;
}
