/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package poke;

import controlador.control_asignar;
import java.applet.AudioClip;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author ANDRES
 */
public class Intefaz_principal extends javax.swing.JFrame {

    control_asignar ctr = new control_asignar();
    public Intefaz_principal() {
          
        
        
        
        initComponents();
          setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Pokemon");
         setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        tb_entre = new javax.swing.JButton();
        bt_poke = new javax.swing.JButton();
        bt_asig = new javax.swing.JButton();
        bt_cons = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        tb_entre.setBackground(new java.awt.Color(51, 255, 255));
        tb_entre.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        tb_entre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/Ash_icon-icons.com_67492 (1).png"))); // NOI18N
        tb_entre.setText("ENTRENADOR");
        tb_entre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_entreMouseClicked(evt);
            }
        });
        tb_entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_entreActionPerformed(evt);
            }
        });
        jDesktopPane1.add(tb_entre);
        tb_entre.setBounds(220, 190, 280, 105);

        bt_poke.setBackground(new java.awt.Color(204, 204, 0));
        bt_poke.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        bt_poke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/037_Pikachu_icon-icons.com_67297 (1).png"))); // NOI18N
        bt_poke.setText("POKEMON");
        bt_poke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pokeActionPerformed(evt);
            }
        });
        jDesktopPane1.add(bt_poke);
        bt_poke.setBounds(800, 200, 260, 110);

        bt_asig.setBackground(new java.awt.Color(255, 51, 0));
        bt_asig.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        bt_asig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/006_Charizard_icon-icons.com_67329.png"))); // NOI18N
        bt_asig.setText("ASIGNAR POKEMON");
        bt_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_asigActionPerformed(evt);
            }
        });
        jDesktopPane1.add(bt_asig);
        bt_asig.setBounds(750, 360, 340, 110);

        bt_cons.setBackground(new java.awt.Color(51, 255, 0));
        bt_cons.setFont(new java.awt.Font("Bungee Inline", 0, 18)); // NOI18N
        bt_cons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/Rayquaza_icon-icons.com_67460.png"))); // NOI18N
        bt_cons.setText("CONSULTA");
        bt_cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consActionPerformed(evt);
            }
        });
        jDesktopPane1.add(bt_cons);
        bt_cons.setBounds(210, 360, 280, 100);

        jButton2.setText("jButton2");
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(780, 440, 73, 23);

        jButton3.setText("jButton3");
        jDesktopPane1.add(jButton3);
        jButton3.setBounds(800, 260, 73, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trainerbattles_opt.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1190, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_consActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consActionPerformed
        Interfaz_consulta nota = new Interfaz_consulta();
        jDesktopPane1.add(nota);
        nota.show();
    }//GEN-LAST:event_bt_consActionPerformed

    private void bt_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_asigActionPerformed
        String est = JOptionPane.showInputDialog(this,"Ingrese el 'ID': ",JOptionPane.OK_OPTION);
        if(ctr.existe_entrenador(est))
        {
            Interfaz_asignar matric = new Interfaz_asignar(ctr);
            jDesktopPane1.add(matric);
            matric.show();
        }
        else
        {

            JOptionPane.showMessageDialog(null,"EL ID NO SE RECONOCE, 'DEBE REGISTRARSE'","Mensaje",JOptionPane.QUESTION_MESSAGE);
        }

    }//GEN-LAST:event_bt_asigActionPerformed

    private void bt_pokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pokeActionPerformed
        Interfaz_pokemon mat = new Interfaz_pokemon();
        jDesktopPane1.add(mat);
        mat.show();
    }//GEN-LAST:event_bt_pokeActionPerformed

    private void tb_entreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_entreActionPerformed
        Interfaz_entrenador estu = new Interfaz_entrenador();
        jDesktopPane1.add(estu);
        estu.show();

    }//GEN-LAST:event_tb_entreActionPerformed

    private void tb_entreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_entreMouseClicked
        //AudioClip sonido;
        //sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Interfaz_principal/pokemon_intro_gameboy.mp3"));
        //sonido.play();
    }//GEN-LAST:event_tb_entreMouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intefaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intefaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intefaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intefaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Intefaz_principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_asig;
    private javax.swing.JButton bt_cons;
    private javax.swing.JButton bt_poke;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton tb_entre;
    // End of variables declaration//GEN-END:variables
}
